// packages/react/src/LunarDatePicker.tsx
import { useEffect, useRef, useState } from 'react'
import { createPortal } from 'react-dom'
import { DatePickerCore } from '../../core/src/date-picker/DatePickerCore'
import { resolveLocale } from '../../core/src/locale'
import type { CalendarMode, CalendarType, DateResult, PickerLocale } from '../../core/src/types'

interface LunarDatePickerProps {
  show?: boolean
  value?: Date
  calendarMode?: CalendarMode
  defaultCalendar?: CalendarType
  startYear?: number
  endYear?: number
  color?: string
  locale?: PickerLocale
  onUpdateShow?: (val: boolean) => void
  onUpdateValue?: (val: Date) => void
  onConfirm?: (result: DateResult) => void
  onCancel?: () => void
  onChange?: (result: DateResult) => void
}

function getInitialCalendar(calendarMode: CalendarMode, defaultCalendar: CalendarType): CalendarType {
  if (calendarMode === 'solar') return 'solar'
  if (calendarMode === 'lunar') return 'lunar'
  return defaultCalendar
}

export function LunarDatePicker({
  show = false,
  value,
  calendarMode = 'switch',
  defaultCalendar = 'solar',
  startYear,
  endYear,
  color = '#D03F3F',
  locale,
  onUpdateShow,
  onUpdateValue,
  onConfirm,
  onCancel,
  onChange
}: LunarDatePickerProps) {
  const containerRef = useRef<HTMLDivElement>(null)
  const coreRef = useRef<DatePickerCore | null>(null)
  const defaultValueRef = useRef<Date>(value ?? new Date())
  const resolvedValue = value ?? defaultValueRef.current
  const [visible, setVisible] = useState(false)
  const [animating, setAnimating] = useState(false)
  const [activeCalendar, setActiveCalendar] = useState<CalendarType>(
    getInitialCalendar(calendarMode, defaultCalendar)
  )
  const labels = resolveLocale(locale)

  function initCore() {
    if (!containerRef.current) return
    coreRef.current?.destroy()
    const initialCalendar = getInitialCalendar(calendarMode, defaultCalendar)
    setActiveCalendar(initialCalendar)
    coreRef.current = new DatePickerCore(containerRef.current, {
      defaultDate: resolvedValue,
      calendarMode,
      defaultCalendar,
      startYear,
      endYear,
      primaryColor: color,
      locale,
      onChange: result => onChange?.(result)
    })
  }

  useEffect(() => {
    if (show) {
      setVisible(true)
      const timer = setTimeout(() => {
        initCore()
        requestAnimationFrame(() => setAnimating(true))
      }, 0)
      return () => clearTimeout(timer)
    } else {
      setAnimating(false)
      const timer = setTimeout(() => {
        setVisible(false)
        coreRef.current?.destroy()
        coreRef.current = null
      }, 300)
      return () => clearTimeout(timer)
    }
  }, [show, resolvedValue, calendarMode, defaultCalendar, startYear, endYear, color, locale, onChange])

  useEffect(() => {
    return () => { coreRef.current?.destroy() }
  }, [])

  function toggleLunar() {
    const next = activeCalendar === 'lunar' ? 'solar' : 'lunar'
    setActiveCalendar(next)
    coreRef.current?.switchCalendarType(next)
  }

  function handleConfirm() {
    if (!coreRef.current) return
    const result = coreRef.current.getResult()
    onUpdateValue?.(result.date)
    onUpdateShow?.(false)
    onConfirm?.(result)
  }

  function handleCancel() {
    onUpdateShow?.(false)
    onCancel?.()
  }

  if (!visible) return null

  return createPortal(
    <div className="ldp-overlay">
      <div
        className={`ldp-mask${animating ? '' : ' ldp-leave'}`}
        onClick={handleCancel}
      />
      <div
        className={`ldp-layout${animating ? ' ldp-show' : ''}`}
        style={{ '--ldp-primary': color } as React.CSSProperties}
        onClick={e => e.stopPropagation()}
      >
        <div className="ldp-header">
          <div className="ldp-cancel" onClick={handleCancel}>{labels.cancel}</div>
          <div />
          <div className="ldp-confirm" onClick={handleConfirm}>{labels.confirm}</div>
        </div>

        <div ref={containerRef} className="ldp-container" />

        {calendarMode === 'switch' && (
          <div className="ldp-footer">
            <div
              className={`ldp-lunar-toggle${activeCalendar === 'lunar' ? ' active' : ''}`}
              onClick={toggleLunar}
            >
              <div className="ldp-lunar-circle" />
              <span>{labels.lunar}</span>
            </div>
          </div>
        )}
      </div>
    </div>,
    document.body
  )
}

// packages/vue/src/LunarDatePicker.vue
<script setup lang="ts">
import { computed, ref, watch, nextTick, onUnmounted } from 'vue'
import { DatePickerCore } from '../../core/src/date-picker/DatePickerCore'
import { resolveLocale } from '../../core/src/locale'
import type { CalendarMode, CalendarType, DateResult, PickerLocale } from '../../core/src/types'

interface Props {
  show?: boolean
  value?: Date
  calendarMode?: CalendarMode
  defaultCalendar?: CalendarType
  startYear?: number
  endYear?: number
  color?: string
  locale?: PickerLocale
}

interface Emits {
  (e: 'update:show', val: boolean): void
  (e: 'update:value', val: Date): void
  (e: 'confirm', result: DateResult): void
  (e: 'cancel'): void
  (e: 'change', result: DateResult): void
}

const props = withDefaults(defineProps<Props>(), {
  show: false,
  value: () => new Date(),
  calendarMode: 'switch',
  defaultCalendar: 'solar',
  startYear: undefined,
  endYear: () => new Date().getFullYear(),
  color: '#D03F3F',
  locale: undefined
})

const emit = defineEmits<Emits>()

const containerRef = ref<HTMLElement>()
const visible = ref(false)
const animating = ref(false)
const activeCalendar = ref<CalendarType>(getInitialCalendar(props.calendarMode, props.defaultCalendar))
const labels = computed(() => resolveLocale(props.locale))

let core: DatePickerCore | null = null

function getInitialCalendar(calendarMode: CalendarMode, defaultCalendar: CalendarType): CalendarType {
  if (calendarMode === 'solar') return 'solar'
  if (calendarMode === 'lunar') return 'lunar'
  return defaultCalendar
}

function initCore() {
  if (!containerRef.value) return
  core?.destroy()
  activeCalendar.value = getInitialCalendar(props.calendarMode, props.defaultCalendar)
  core = new DatePickerCore(containerRef.value, {
    defaultDate: props.value,
    calendarMode: props.calendarMode,
    defaultCalendar: props.defaultCalendar,
    startYear: props.startYear,
    endYear: props.endYear,
    primaryColor: props.color,
    locale: props.locale,
    onChange: result => emit('change', result)
  })
}

watch(
  () => props.show,
  async val => {
    if (val) {
      visible.value = true
      await nextTick()
      initCore()
      requestAnimationFrame(() => {
        animating.value = true
      })
    } else {
      animating.value = false
      setTimeout(() => {
        visible.value = false
        core?.destroy()
        core = null
      }, 300)
    }
  }
)

watch(
  () => props.value,
  val => {
    if (val && core) core.setDate(val)
  }
)

watch(
  () => [props.calendarMode, props.defaultCalendar] as const,
  ([calendarMode, defaultCalendar]) => {
    const nextCalendar = getInitialCalendar(calendarMode, defaultCalendar)
    activeCalendar.value = nextCalendar
    core?.switchCalendarType(nextCalendar)
  }
)

function toggleLunar() {
  activeCalendar.value = activeCalendar.value === 'lunar' ? 'solar' : 'lunar'
  core?.switchCalendarType(activeCalendar.value)
}

function handleConfirm() {
  if (!core) return
  const result = core.getResult()
  emit('update:value', result.date)
  emit('update:show', false)
  emit('confirm', result)
}

function handleCancel() {
  emit('update:show', false)
  emit('cancel')
}

onUnmounted(() => core?.destroy())
</script>

<template>
  <Teleport to="body">
    <div
      v-if="visible"
      class="ldp-overlay"
    >
      <div
        class="ldp-mask"
        :class="{ 'ldp-leave': !animating }"
        @click="handleCancel"
      />
      <div
        class="ldp-layout"
        :class="{ 'ldp-show': animating }"
        :style="{ '--ldp-primary': color }"
        @click.stop
      >
        <div class="ldp-header">
          <div
            class="ldp-cancel"
            @click="handleCancel"
          >
            {{ labels.cancel }}
          </div>
          <div />
          <div
            class="ldp-confirm"
            @click="handleConfirm"
          >
            {{ labels.confirm }}
          </div>
        </div>

        <div
          ref="containerRef"
          class="ldp-container"
        />

        <div
          v-if="calendarMode === 'switch'"
          class="ldp-footer"
        >
          <div
            class="ldp-lunar-toggle"
            :class="{ active: activeCalendar === 'lunar' }"
            @click="toggleLunar"
          >
            <div class="ldp-lunar-circle" />
            <span>{{ labels.lunar }}</span>
          </div>
        </div>
      </div>
    </div>
  </Teleport>
</template>
