// packages/react/src/LunarDateTimePicker.tsx
import { useEffect, useRef, useState } from 'react'
import { createPortal } from 'react-dom'
import { DateTimePickerCore } from '../../core/src/datetime-picker/DateTimePickerCore'
import { resolveLocale } from '../../core/src/locale'
import type {
  CalendarMode,
  CalendarType,
  DateTimeResult,
  PickerLocale,
  TimeField
} from '../../core/src/types'

interface LunarDateTimePickerProps {
  show?: boolean
  value?: Date
  calendarMode?: CalendarMode
  defaultCalendar?: CalendarType
  timeFields?: TimeField[]
  showUnit?: boolean
  showUnclear?: boolean
  unclearPosition?: 'first' | 'last'
  startYear?: number
  endYear?: number
  color?: string
  locale?: PickerLocale
  onUpdateShow?: (val: boolean) => void
  onUpdateValue?: (val: Date) => void
  onConfirm?: (result: DateTimeResult) => void
  onCancel?: () => void
  onChange?: (result: DateTimeResult) => void
}

const DEFAULT_TIME_FIELDS: TimeField[] = ['hour', 'minute']

function getInitialCalendar(calendarMode: CalendarMode, defaultCalendar: CalendarType): CalendarType {
  if (calendarMode === 'solar') return 'solar'
  if (calendarMode === 'lunar') return 'lunar'
  return defaultCalendar
}

export function LunarDateTimePicker({
  show = false,
  value,
  calendarMode = 'switch',
  defaultCalendar = 'solar',
  timeFields,
  showUnit = true,
  showUnclear = true,
  unclearPosition = 'last',
  startYear,
  endYear,
  color = '#D03F3F',
  locale,
  onUpdateShow,
  onUpdateValue,
  onConfirm,
  onCancel,
  onChange
}: LunarDateTimePickerProps) {
  const containerRef = useRef<HTMLDivElement>(null)
  const coreRef = useRef<DateTimePickerCore | null>(null)
  const defaultValueRef = useRef<Date>(value ?? new Date())
  const resolvedValue = value ?? defaultValueRef.current
  const resolvedTimeFields = timeFields ?? DEFAULT_TIME_FIELDS
  const timeFieldsKey = resolvedTimeFields.join(',')
  const [visible, setVisible] = useState(false)
  const [animating, setAnimating] = useState(false)
  const [activeTab, setActiveTab] = useState<CalendarType>(
    getInitialCalendar(calendarMode, defaultCalendar)
  )
  const labels = resolveLocale(locale)

  function initCore() {
    if (!containerRef.current) return
    coreRef.current?.destroy()
    setActiveTab(getInitialCalendar(calendarMode, defaultCalendar))
    coreRef.current = new DateTimePickerCore(containerRef.current, {
      defaultDate: resolvedValue,
      calendarMode,
      defaultCalendar,
      timeFields: resolvedTimeFields,
      showUnit,
      showUnclear,
      unclearPosition,
      startYear,
      endYear,
      primaryColor: color,
      locale,
      onChange: result => onChange?.(result),
      onConfirm: () => {},
      onCancel: () => {}
    })
  }

  useEffect(() => {
    if (show) {
      setVisible(true)
      const timer = setTimeout(() => {
        initCore()
        requestAnimationFrame(() => setAnimating(true))
      }, 0)
      return () => clearTimeout(timer)
    } else {
      setAnimating(false)
      const timer = setTimeout(() => {
        setVisible(false)
        coreRef.current?.destroy()
        coreRef.current = null
      }, 300)
      return () => clearTimeout(timer)
    }
  }, [
    show,
    resolvedValue,
    calendarMode,
    defaultCalendar,
    timeFieldsKey,
    showUnit,
    showUnclear,
    unclearPosition,
    startYear,
    endYear,
    color,
    locale,
    onChange
  ])

  useEffect(() => {
    if (resolvedValue && coreRef.current) coreRef.current.setDate(resolvedValue)
  }, [resolvedValue])

  useEffect(() => {
    const nextTab = getInitialCalendar(calendarMode, defaultCalendar)
    setActiveTab(nextTab)
    coreRef.current?.switchCalendarType(nextTab)
  }, [calendarMode, defaultCalendar])

  useEffect(() => {
    return () => { coreRef.current?.destroy() }
  }, [])

  function switchTab(tab: 'solar' | 'lunar') {
    if (activeTab === tab) return
    setActiveTab(tab)
    coreRef.current?.switchCalendarType(tab)
  }

  function handleConfirm() {
    if (!coreRef.current) return
    const result = coreRef.current.getResult()
    onUpdateValue?.(result.date)
    onUpdateShow?.(false)
    onConfirm?.(result)
  }

  function handleCancel() {
    onUpdateShow?.(false)
    onCancel?.()
  }

  if (!visible) return null

  return createPortal(
    <div className="ldp-overlay">
      <div
        className={`ldp-mask${animating ? '' : ' ldp-leave'}`}
        onClick={handleCancel}
      />
      <div
        className={`ldp-layout${animating ? ' ldp-show' : ''}`}
        style={{ '--ldp-primary': color } as React.CSSProperties}
        onClick={e => e.stopPropagation()}
      >
        <div className="ldp-header">
          <div className="ldp-cancel" onClick={handleCancel}>{labels.cancel}</div>

          {calendarMode === 'switch' ? (
            <div className="ldp-btn-group">
              <div
                className={`ldp-solar-btn ldp-btn${activeTab === 'solar' ? ' active' : ''}`}
                onClick={() => switchTab('solar')}
              >
                {labels.solar}
              </div>
              <div
                className={`ldp-lunar-btn ldp-btn${activeTab === 'lunar' ? ' active' : ''}`}
                onClick={() => switchTab('lunar')}
              >
                {labels.lunar}
              </div>
            </div>
          ) : <div />}

          <div className="ldp-confirm" onClick={handleConfirm}>{labels.confirm}</div>
        </div>

        <div ref={containerRef} className="ldp-container" />
      </div>
    </div>,
    document.body
  )
}

// packages/vue/src/LunarDateTimePicker.vue
<script setup lang="ts">
import { computed, ref, watch, nextTick, onUnmounted } from 'vue'
import { DateTimePickerCore } from '../../core/src/datetime-picker/DateTimePickerCore'
import { resolveLocale } from '../../core/src/locale'
import type {
  CalendarMode,
  CalendarType,
  DateTimeResult,
  PickerLocale,
  TimeField
} from '../../core/src/types'

interface Props {
  show?: boolean
  value?: Date
  calendarMode?: CalendarMode
  defaultCalendar?: CalendarType
  timeFields?: TimeField[]
  showUnit?: boolean
  showUnclear?: boolean
  unclearPosition?: 'first' | 'last'
  startYear?: number
  endYear?: number
  color?: string
  locale?: PickerLocale
}

interface Emits {
  (e: 'update:show', val: boolean): void
  (e: 'update:value', val: Date): void
  (e: 'confirm', result: DateTimeResult): void
  (e: 'cancel'): void
  (e: 'change', result: DateTimeResult): void
}

const props = withDefaults(defineProps<Props>(), {
  show: false,
  value: () => new Date(),
  calendarMode: 'switch',
  defaultCalendar: 'solar',
  timeFields: () => ['hour', 'minute'],
  showUnit: true,
  showUnclear: true,
  unclearPosition: 'last',
  startYear: undefined,
  endYear: () => new Date().getFullYear(),
  color: '#D03F3F',
  locale: undefined
})

const emit = defineEmits<Emits>()

const containerRef = ref<HTMLElement>()
const visible = ref(false)
const animating = ref(false)
const activeTab = ref<CalendarType>(getInitialCalendar(props.calendarMode, props.defaultCalendar))
const labels = computed(() => resolveLocale(props.locale))

let core: DateTimePickerCore | null = null

function getInitialCalendar(calendarMode: CalendarMode, defaultCalendar: CalendarType): CalendarType {
  if (calendarMode === 'solar') return 'solar'
  if (calendarMode === 'lunar') return 'lunar'
  return defaultCalendar
}

function initCore() {
  if (!containerRef.value) return
  core?.destroy()
  activeTab.value = getInitialCalendar(props.calendarMode, props.defaultCalendar)
  core = new DateTimePickerCore(containerRef.value, {
    defaultDate: props.value,
    calendarMode: props.calendarMode,
    defaultCalendar: props.defaultCalendar,
    timeFields: props.timeFields,
    showUnit: props.showUnit,
    showUnclear: props.showUnclear,
    unclearPosition: props.unclearPosition,
    startYear: props.startYear,
    endYear: props.endYear,
    primaryColor: props.color,
    locale: props.locale,
    onChange: result => emit('change', result),
    onConfirm: () => {},
    onCancel: () => {}
  })
}

watch(
  () => props.show,
  async val => {
    if (val) {
      visible.value = true
      await nextTick()
      initCore()
      requestAnimationFrame(() => {
        animating.value = true
      })
    } else {
      animating.value = false
      setTimeout(() => {
        visible.value = false
        core?.destroy()
        core = null
      }, 300)
    }
  }
)

watch(
  () => props.value,
  val => {
    if (val && core) core.setDate(val)
  }
)

watch(
  () => [props.calendarMode, props.defaultCalendar] as const,
  ([calendarMode, defaultCalendar]) => {
    const nextTab = getInitialCalendar(calendarMode, defaultCalendar)
    activeTab.value = nextTab
    core?.switchCalendarType(nextTab)
  }
)

function switchTab(tab: 'solar' | 'lunar') {
  if (activeTab.value === tab) return
  activeTab.value = tab
  core?.switchCalendarType(tab)
}

function handleConfirm() {
  if (!core) return
  const result = core.getResult()
  emit('update:value', result.date)
  emit('update:show', false)
  emit('confirm', result)
}

function handleCancel() {
  emit('update:show', false)
  emit('cancel')
}

onUnmounted(() => {
  core?.destroy()
})
</script>

<template>
  <Teleport to="body">
    <div
      v-if="visible"
      class="ldp-overlay"
    >
      <div
        class="ldp-mask"
        :class="{ 'ldp-leave': !animating }"
        @click="handleCancel"
      />

      <div
        class="ldp-layout"
        :class="{ 'ldp-show': animating }"
        :style="{ '--ldp-primary': color }"
        @click.stop
      >
        <div class="ldp-header">
          <div
            class="ldp-cancel"
            @click="handleCancel"
          >
            {{ labels.cancel }}
          </div>

          <div
            v-if="calendarMode === 'switch'"
            class="ldp-btn-group"
          >
            <div
              class="ldp-solar-btn ldp-btn"
              :class="{ active: activeTab === 'solar' }"
              @click="switchTab('solar')"
            >
              {{ labels.solar }}
            </div>
            <div
              class="ldp-lunar-btn ldp-btn"
              :class="{ active: activeTab === 'lunar' }"
              @click="switchTab('lunar')"
            >
              {{ labels.lunar }}
            </div>
          </div>
          <div v-else />

          <div
            class="ldp-confirm"
            @click="handleConfirm"
          >
            {{ labels.confirm }}
          </div>
        </div>

        <div
          ref="containerRef"
          class="ldp-container"
        />
      </div>
    </div>
  </Teleport>
</template>
