// src/vue/LunarDateTimePicker.vue
<script setup lang="ts">
import { ref, watch, nextTick, onUnmounted } from 'vue'
import { DateTimePickerCore } from '../core/datetime-picker/DateTimePickerCore'
import type { DateTimeResult } from '../core/types'
import type { PickerType, TimeField } from '../core/types'

interface Props {
  show?: boolean
  value?: Date
  type?: PickerType // 0: 只公历, 1: 公历+农历切换, 2: 默认农历
  timeFields?: TimeField[] // 要显示的时间字段，例如 ['hour', 'minute'] 或 ['hour', 'minute', 'second']
  showUnit?: boolean // 是否显示单位文字（年、月、日、时、分、秒）
  unclearFirst?: boolean // "不清楚"选项是否放在时间列的最前面
  endYear?: number
  color?: string
  confirmText?: string
  cancelText?: string
}

interface Emits {
  (e: 'update:show', val: boolean): void
  (e: 'update:value', val: Date): void
  (e: 'confirm', result: DateTimeResult): void
  (e: 'cancel'): void
  (e: 'change', result: DateTimeResult): void
}

const props = withDefaults(defineProps<Props>(), {
  show: false,
  value: () => new Date(),
  type: 1,
  timeFields: () => ['hour', 'minute'],
  showUnit: true,
  unclearFirst: false,
  endYear: () => new Date().getFullYear(),
  color: '#D03F3F',
  confirmText: '确定',
  cancelText: '取消'
})

const emit = defineEmits<Emits>()

const containerRef = ref<HTMLElement>()
const visible = ref(false)
const animating = ref(false)
const activeTab = ref<'solar' | 'lunar'>(typeToTab(props.type))

let core: DateTimePickerCore | null = null

function typeToTab(type: PickerType): 'solar' | 'lunar' {
  return type === 2 ? 'lunar' : 'solar'
}

function initCore() {
  if (!containerRef.value) return
  core?.destroy()
  activeTab.value = typeToTab(props.type)
  core = new DateTimePickerCore(containerRef.value, {
    defaultDate: props.value,
    type: props.type,
    timeFields: props.timeFields,
    showUnit: props.showUnit,
    unclearFirst: props.unclearFirst,
    endYear: props.endYear,
    primaryColor: props.color,
    onChange: result => emit('change', result),
    onConfirm: () => {},
    onCancel: () => {}
  })
}

watch(
  () => props.show,
  async val => {
    if (val) {
      visible.value = true
      await nextTick()
      initCore()
      requestAnimationFrame(() => {
        animating.value = true
      })
    } else {
      animating.value = false
      setTimeout(() => {
        visible.value = false
        core?.destroy()
        core = null
      }, 300)
    }
  }
)

watch(
  () => props.value,
  val => {
    if (val && core) core.setDate(val)
  }
)

watch(
  () => props.type,
  val => {
    const nextTab = typeToTab(val)
    activeTab.value = nextTab
    core?.switchCalendarType(nextTab)
  }
)

function switchTab(tab: 'solar' | 'lunar') {
  if (activeTab.value === tab) return
  activeTab.value = tab
  core?.switchCalendarType(tab)
}

function handleConfirm() {
  if (!core) return
  const result = core.getResult()
  emit('update:value', result.date)
  emit('update:show', false)
  emit('confirm', result)
}

function handleCancel() {
  emit('update:show', false)
  emit('cancel')
}

onUnmounted(() => {
  core?.destroy()
})
</script>

<template>
  <Teleport to="body">
    <div
      v-if="visible"
      class="ldp-overlay"
    >
      <!-- 遮罩 -->
      <div
        class="ldp-mask"
        :class="{ 'ldp-leave': !animating }"
        @click="handleCancel"
      />

      <!-- 面板 -->
      <div
        class="ldp-layout"
        :class="{ 'ldp-show': animating }"
        :style="{ '--ldp-primary': color }"
        @click.stop
      >
        <!-- 头部 -->
        <div class="ldp-header">
          <div
            class="ldp-cancel"
            @click="handleCancel"
          >
            {{ cancelText }}
          </div>

          <!-- 公历/农历切换（type !== 0 时显示） -->
          <div
            v-if="type !== 0"
            class="ldp-btn-group"
          >
            <div
              class="ldp-solar-btn ldp-btn"
              :class="{ active: activeTab === 'solar' }"
              @click="switchTab('solar')"
            >
              公历
            </div>
            <div
              class="ldp-lunar-btn ldp-btn"
              :class="{ active: activeTab === 'lunar' }"
              @click="switchTab('lunar')"
            >
              农历
            </div>
          </div>
          <div v-else />

          <div
            class="ldp-confirm"
            @click="handleConfirm"
          >
            {{ confirmText }}
          </div>
        </div>

        <!-- 滚动列容器 -->
        <div
          ref="containerRef"
          class="ldp-container"
        />
      </div>
    </div>
  </Teleport>
</template>

// src/react/LunarDateTimePicker.tsx
import { useEffect, useRef, useState } from 'react'
import { createPortal } from 'react-dom'
import { DateTimePickerCore } from '../core/datetime-picker/DateTimePickerCore'
import type { DateTimeResult, PickerType, TimeField } from '../core/types'

interface LunarDateTimePickerProps {
  show?: boolean
  value?: Date
  type?: PickerType
  timeFields?: TimeField[]
  showUnit?: boolean
  unclearFirst?: boolean
  endYear?: number
  color?: string
  confirmText?: string
  cancelText?: string
  onUpdateShow?: (val: boolean) => void
  onUpdateValue?: (val: Date) => void
  onConfirm?: (result: DateTimeResult) => void
  onCancel?: () => void
  onChange?: (result: DateTimeResult) => void
}

function typeToTab(type: PickerType): 'solar' | 'lunar' {
  return type === 2 ? 'lunar' : 'solar'
}

export function LunarDateTimePicker({
  show = false,
  value = new Date(),
  type = 1,
  timeFields = ['hour', 'minute'],
  showUnit = true,
  unclearFirst = false,
  endYear = new Date().getFullYear(),
  color = '#D03F3F',
  confirmText = '确定',
  cancelText = '取消',
  onUpdateShow,
  onUpdateValue,
  onConfirm,
  onCancel,
  onChange
}: LunarDateTimePickerProps) {
  const containerRef = useRef<HTMLDivElement>(null)
  const coreRef = useRef<DateTimePickerCore | null>(null)
  const [visible, setVisible] = useState(false)
  const [animating, setAnimating] = useState(false)
  const [activeTab, setActiveTab] = useState<'solar' | 'lunar'>(typeToTab(type))

  function initCore() {
    if (!containerRef.current) return
    coreRef.current?.destroy()
    setActiveTab(typeToTab(type))
    coreRef.current = new DateTimePickerCore(containerRef.current, {
      defaultDate: value,
      type,
      timeFields,
      showUnit,
      unclearFirst,
      endYear,
      primaryColor: color,
      onChange: result => onChange?.(result),
      onConfirm: () => {},
      onCancel: () => {}
    })
  }

  useEffect(() => {
    if (show) {
      setVisible(true)
      const timer = setTimeout(() => {
        initCore()
        requestAnimationFrame(() => setAnimating(true))
      }, 0)
      return () => clearTimeout(timer)
    } else {
      setAnimating(false)
      const timer = setTimeout(() => {
        setVisible(false)
        coreRef.current?.destroy()
        coreRef.current = null
      }, 300)
      return () => clearTimeout(timer)
    }
  }, [show, value, timeFields, showUnit, unclearFirst, endYear, color, onChange])

  useEffect(() => {
    if (value && coreRef.current) coreRef.current.setDate(value)
  }, [value])

  useEffect(() => {
    const nextTab = typeToTab(type)
    setActiveTab(nextTab)
    coreRef.current?.switchCalendarType(nextTab)
  }, [type])

  useEffect(() => {
    return () => { coreRef.current?.destroy() }
  }, [])

  function switchTab(tab: 'solar' | 'lunar') {
    if (activeTab === tab) return
    setActiveTab(tab)
    coreRef.current?.switchCalendarType(tab)
  }

  function handleConfirm() {
    if (!coreRef.current) return
    const result = coreRef.current.getResult()
    onUpdateValue?.(result.date)
    onUpdateShow?.(false)
    onConfirm?.(result)
  }

  function handleCancel() {
    onUpdateShow?.(false)
    onCancel?.()
  }

  if (!visible) return null

  return createPortal(
    <div className="ldp-overlay">
      <div
        className={`ldp-mask${animating ? '' : ' ldp-leave'}`}
        onClick={handleCancel}
      />
      <div
        className={`ldp-layout${animating ? ' ldp-show' : ''}`}
        style={{ '--ldp-primary': color } as React.CSSProperties}
        onClick={e => e.stopPropagation()}
      >
        <div className="ldp-header">
          <div className="ldp-cancel" onClick={handleCancel}>{cancelText}</div>

          {type !== 0 ? (
            <div className="ldp-btn-group">
              <div
                className={`ldp-solar-btn ldp-btn${activeTab === 'solar' ? ' active' : ''}`}
                onClick={() => switchTab('solar')}
              >
                公历
              </div>
              <div
                className={`ldp-lunar-btn ldp-btn${activeTab === 'lunar' ? ' active' : ''}`}
                onClick={() => switchTab('lunar')}
              >
                农历
              </div>
            </div>
          ) : <div />}

          <div className="ldp-confirm" onClick={handleConfirm}>{confirmText}</div>
        </div>

        <div ref={containerRef} className="ldp-container" />
      </div>
    </div>,
    document.body
  )
}
